image: docker:stable

variables:
  DOCKER_DRIVER: overlay2

services:
    - docker:dind

before_script:
    - docker info

build:
    stage: build
    script:
      - cd gamma_dev 
      - docker build -f Dockerfile -t $CI_REGISTRY_IMAGE .
      - docker push $CI_REGISTRY_IMAGE